Ensure parsed configuration is a Hash
Setting up packwerk caused a bug during the initial `packwerk check`:

```
bundler: failed to load command: packwerk (/Users/alexblackie/.gem/ruby/2.6.6/bin/packwerk)
NoMethodError: undefined method `[]' for false:FalseClass
  /Users/alexblackie/.gem/ruby/2.6.6/gems/packwerk-1.1.0/lib/packwerk/configuration.rb:39:in `initialize'
  /Users/alexblackie/.gem/ruby/2.6.6/gems/packwerk-1.1.0/lib/packwerk/configuration.rb:25:in `new'
```

This appears to have been because the YAML configuration file that is
generated is empty (comments only) by default, causing `load_file` to
return `false` because it isn't yet a valid YAML document.

To ensure we comply with the API of `Configuration`, we should ensure
any falsey values get turned into an empty hash.

Co-authored-by: Jacob Erickson <jacob.erickson@shopify.com>